In [1]:
# Exception Handling
def invert(x):
    ans=1/x
    return ans
print('1/4 =', invert(4))
print('1/0.5 =',invert(0.5))
print('1/0 =',invert(0))

1/4 = 0.25
1/0.5 = 2.0


ZeroDivisionError: division by zero

In [2]:
# Exception Handling
def invert(x):
    ans=1/x
    return ans
print('1/0 =',invert(0))
print('1/4 =', invert(4))
print('1/0.5 =',invert(0.5))


ZeroDivisionError: division by zero

In [9]:
def invert(x):
    ans = None
    try:
        ans=1/x
    except Exception as err:
        pass
    return ans
inputs = [0, 4, 0.5, 'apple', [2,3]]
for x in inputs:
    ans = invert(x)
    if ans is not None:
        print('1 /',x,'=',ans)
    else:
        print('1 /',x,'is undefined')
# print('1/0 =',invert(0))
# print('1/4 =', invert(4))
# print('1/0.5 =',invert(0.5))

1 / 0 is undefined
1 / 4 = 0.25
1 / 0.5 = 2.0
1 / apple is undefined
1 / [2, 3] is undefined


In [10]:
# Numpy

import numpy as np


In [11]:
data = 10 * np.random.randn(2,3,4)

In [12]:
print(data)

[[[-13.74726831   3.50466582  -4.73128827   2.62880122]
  [ -3.83648115 -12.3964686    9.38678023  -6.10317972]
  [ -6.4161903   23.64699449  -8.25510433  -4.12504565]]

 [[-21.43230688  10.81137743   0.69928884  -8.57289829]
  [ 14.40616604  -8.1456314   -2.30986128  13.10994131]
  [-16.2505641    1.81788955 -15.34696113 -15.69838722]]]


In [13]:
data = np.round(10 * np.random.randn(2,3,4))
print(data)

[[[  7.   5. -14.  -2.]
  [-10.  -0.   3.   9.]
  [  8.  22.  -9. -14.]]

 [[ 20. -17.  -2.   3.]
  [  4.   1.  11.  -2.]
  [ -1. -12.  -3.   4.]]]


In [15]:
print(data[1],'\n')

[[ 20. -17.  -2.   3.]
 [  4.   1.  11.  -2.]
 [ -1. -12.  -3.   4.]] 



In [16]:
# [ : ] => All elements
# [a : b] => a to b (exclusive)
# [a :] => from index a till end
# [:b] => from start to index b(exclusive)

In [17]:
print(data, '\n')
print(data[:, 1:, :])

[[[  7.   5. -14.  -2.]
  [-10.  -0.   3.   9.]
  [  8.  22.  -9. -14.]]

 [[ 20. -17.  -2.   3.]
  [  4.   1.  11.  -2.]
  [ -1. -12.  -3.   4.]]] 

[[[-10.  -0.   3.   9.]
  [  8.  22.  -9. -14.]]

 [[  4.   1.  11.  -2.]
  [ -1. -12.  -3.   4.]]]


In [18]:
print(data, '\n')
print(data[:, 1:, 1:3])

[[[  7.   5. -14.  -2.]
  [-10.  -0.   3.   9.]
  [  8.  22.  -9. -14.]]

 [[ 20. -17.  -2.   3.]
  [  4.   1.  11.  -2.]
  [ -1. -12.  -3.   4.]]] 

[[[ -0.   3.]
  [ 22.  -9.]]

 [[  1.  11.]
  [-12.  -3.]]]


In [20]:
print(np.ones((2,2,2,3)),'\n') #zeroes

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]] 



In [21]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
data=np.matrix([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [25]:
print(data.shape)

(2, 2)


In [26]:
print(np.sqrt(data))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
data=np.matrix([[1,2],[3,4],[5,6]])
print(data,'\n')
print(data.T.dot(data),'\n')
print(np.dot(data.T, data))

[[1 2]
 [3 4]
 [5 6]] 

[[35 44]
 [44 56]] 

[[35 44]
 [44 56]]
